@url = http://localhost:3001

### Create a new user
POST {{url}}/auth/signup
content-type: application/json

{
    "email": "cccc@aaaaa.com",
    "password": "wwwwwww"
}

### Signin a new user
POST {{url}}/auth/signin
content-type: application/json

{
    "email": "cccc@aaaaa.com",
    "password": "wwwwwww"
}

### Signou a new user
POST {{url}}/auth/signout
content-type: application/json

### Get the currently signed in user
GET {{url}}/auth/whoami

### Find a particular user with a given ID
GET {{url}}/auth/1

### Find all users with a given email
GET {{url}}/auth?email=ccc@ddddd.com

### Find all users
GET {{url}}/auth

### Delete a user with a given id
DELETE {{url}}/auth/2

### Update a user
PATCH {{url}}/auth/3123213
content-type: application/json

{
    "email": "aaa@bcd.com.br",
    "password": "Peperoni"
}
